import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "../styles/variables.css";
import "../styles/carousel.css";
import Navbar from "@/components/layout/Navbar";
import ToastProvider from "@/components/ui/ToastProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased theme-light`}
      >
        <ToastProvider>
          <div className="text-black">
            <Navbar />
            <div className="w-screen h-[calc(100vh-64px)] bg-background z-[1] flex overflow-y-scroll">
              {children}
            </div>
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}
